version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - algoliasearch
  - blackletter
  - domcontentloaded
  - Firestore
  - fontshare
  - Futura
  - gjst
  - grotesk
  - instantsearch
  - typewolf
  - Univers
  - upserts
  - wdth
  - webfont
  - webfonts
  - wght
ignoreWords: []
import: []
