export const colorStyles = [
  "black-on-white",
  "white-on-black",
  "red-on-white",
  "red-on-black",
  "white-on-red",
  "black-on-red",
  "blue-on-white",
  "blue-on-black",
  "white-on-blue",
  "black-on-blue",
  "gray-on-white",
  "gray-on-black",
  "white-on-gray",
  "black-on-gray",
];
